### ISSUE TITLE
Add Zone Multiplicity

### ISSUE THREAD

**Issue by courageousillumination** [courageousillumination/deckr#35]
Right now, if you want to create multiple zones you need to write them all out explicitly

```
zones:
   - name: "play_zone1"
     type: "play_zone"
   - name: "play_zone2"
     type: "play_zone"
   ...
```

You should be able to write it out with a special variable that will create multiple zones

```
zones:
    - name: "play_zone"
    - type: "play_zone"
    - multiplicity: 10
```

You could then access the first zone like this:

```
self.play_zone[0]
```
